# pillow-accel Azure Pipelines build

name: $(Date:yyyyMMdd).$(Rev:.r)

jobs:
  - job: Linux
    displayName: Linux build job. Builds all variants with conda build.
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Setup conda path.
      - bash: |
          conda create --yes --quiet --name buildEnv conda-build conda-verify
          source activate buildEnv
          mkdir -p $(Build.ArtifactStagingDirectory)/linux-64/
        displayName: Setup job
      - bash: |
          source activate buildEnv
          conda build --output-folder "$(Build.ArtifactStagingDirectory)" .
        workingDirectory: $(Build.SourcesDirectory)/recipes/_pillow-accel-default/
        displayName: Build defaults metapackage
      - bash: |
          source activate buildEnv
          conda build -c defaults -c conda-forge --output-folder "$(Build.ArtifactStagingDirectory)" .
        workingDirectory: $(Build.SourcesDirectory)/recipes/pillow-accel/
        displayName: Build packages
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/linux-64'
          artifactName: linux64-packages
