# Speicfy both build_str and version number to aid readabilty,
# _pillow-accel-default=0=not-default rather than just _pillow-accel-default=0
version:
  - 0.0
  - 1.0
build_str:
  - "not_default"
  - "default"
zip_keys:
  - version
  - build_str