{% set version = "5.3.0.post1" %}
{% set build_num = "0" %}


# Acceleration options
{% if accel == "avx512" %}
  # Only AVX512 arch in gcc 7.3.0 used by conda
  {% set march = "skylake-avx512" %}
  {% set mtune = "skylake-avx512" %}
{% elif accel == "avx2" %}
  {% set march = "core-avx2" %}
  {% set mtune = "skylake" %}
{% elif accel == "sse4" %}
  {% set march = "nehalem" %}
  {% set mtune = "ivybridge" %}
{% endif %}

# TODO: What happens if we don't have subpackages but just have all packages depend on a
#       different version of a metapackage. Installing another variant should then 
#       uninstall the first to satisfy metapackage version.

package:
  name: pillow-accel-{{ accel }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/p/pillow-simd/Pillow-SIMD-{{ version }}.tar.gz

requirements:
  host:
    - python {{ python }}
  run:
    - {{ pin_subpackage('pillow-accel', exact=True) }}

build:
  number: {{ build_num }}
  string: py{{ CONDA_PY  }}_{{ accel }}_{{ build_num }}

test:
  imports:
    # Only wrapping subpackage which does fuller tests, so just a minimal check here
    - PIL.Image

about:
  home: https://github.com/uploadcare/pillow-simd/
  license: PIL license
  license_family: Other
  license_file: LICENSE
  summary: 'Accelerated version of the friendly PIL fork by Alex Clark and Contributors. For {{ accel|upper }} capable processors.'

extra:
  pillow-accel-variant: py{{ python }}_{{ accel }}

outputs:
  - name: pillow-accel
    build:
      number: {{ build_num }}
      string: py{{ CONDA_PY  }}_{{ accel }}_{{ build_num }}
      script_env:
        - TEST_RESULTS_DIR
      script:
        - ${RECIPE_DIR}/build-linux.sh {{ accel }} # [linux64]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python {{ python }}
        - setuptools
        - pkg-config
        - libjpeg-turbo 2.0.*
        - zlib 1.2.*
        - libtiff 4.0.*
        - freetype 2.6.*
        - tk 8.* # Was 8.5.* but this doesn't work on py37, check this
        - olefile 0.* # Was 0.44 but this doesn't work with py37, check this
      run:
        - python {{ python }}
        - {{ default }} # Metapackage to specify default variant
        # Freetype doesn't specify it's own pinning so do that. Could possibly be upstreamed.
        - {{ pin_compatible('freetype', max_pin='x.x') }}
      run_constrained:
          # libjpeg from version 8 will clobber libjpeg-turbo
          # This will allow anything but 8 so other versions can be installed
          # Should possibly be upstreamed to libjpeg-turbo
          - jpeg !=8.*
    test:
      requires:
        - junit-xml
      files:
        - Tests/images
        - test_runner.py
      source_files:
        - selftest.py
      commands:
        - python test_runner.py --no-status -o "${TEST_RESULTS_DIR-$CONDA_PREFIX/conda-bld/test-results}/test-py{{ CONDA_PY  }}_{{ accel }}-selftest.xml" selftest
      imports:
        - PIL
        - PIL.Image
        - PIL._imaging
        - PIL._imagingft
        - PIL._imagingmath
        - PIL._imagingmorph
        - PIL._imagingtk     #[linux and not (arm or ppc64le)]
      about:
        home: https://github.com/uploadcare/pillow-simd/
        license: PIL license
        license_family: Other
        license_file: LICENSE
        summary: 'Accelerated version of the friendly PIL fork by Alex Clark and Contributors.'
